# Generated by Django 3.0.5 on 2020-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=10, verbose_name='Número')),
                ('tipo_mesa', models.CharField(blank=True, choices=[('min', 'Mineira normal'), ('mip', 'Mineira pequena'), ('tot', 'Totó'), ('mig', 'Mineira grande'), ('cbc', 'Cumbuca'), ('cmp', 'Campineira')], default='min', help_text='Escolha o tipo de mesa', max_length=3)),
                ('num_registro', models.IntegerField(default=0, help_text='O número do registro', max_length=10)),
                ('locada', models.BooleanField(default=False, help_text='Informa se a mesa está locada', verbose_name='Locada')),
            ],
        ),
    ]
