# Generated by Django 3.0.5 on 2020-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='num_registro',
            field=models.IntegerField(default=0, help_text='O número do registro'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
