# Generated by Django 3.0.5 on 2020-04-30 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_auto_20200430_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(help_text='Número da plaqueta da mesa.', unique=True, verbose_name='Número'),
        ),
    ]
