# Generated by Django 3.0.5 on 2020-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0003_auto_20200430_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='locada',
            field=models.BooleanField(default=False, editable=False, help_text='Informa se a mesa está locada', verbose_name='Locada'),
        ),
    ]
