# Generated by Django 3.0.5 on 2020-04-29 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
    ]
