# Generated by Django 3.0.5 on 2020-05-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20200429_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='inativo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
    ]
