# Generated by Django 3.0.5 on 2020-05-01 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20200501_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inativo',
            field=models.BooleanField(default=False, verbose_name='Inativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
    ]
