# Generated by Django 3.0.5 on 2020-05-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20200426_1858'),
        ('funcionario', '0007_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargo.Cargo', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
